### ISSUE TITLE
using-sag-icons

### ISSUE THREAD

**Issue by Phan717** [Phan717/using-svg-icons#1]
Hi Christian,
I still cannot do all commits this exercise. I did not know why? Could you please check it?
Thank you,
Andrea
[using-svg-icons-lesson.zip](https://github.com/Phan717/using-svg-icons/files/7474306/using-svg-icons-lesson.zip)
@thatkidmadrid

**Comment by thatkidmadrid** [comment]
which folder are you trying to push to your repository?

**Comment by thatkidmadrid** [comment]
You always want to confirm that you can push to your repo at the beginning when you clone it so that you don't run into this issue at the end. I'll give you the grade this time, but be please be more careful next time

**Comment by thatkidmadrid** [comment]
also, please don't close the issues until I have addressed it, otherwise I might miss it in my list
